### ISSUE TITLE
NullPointerException for Recipient on Key Exchange Received

### ISSUE THREAD

**Issue by gnu-user** [tinfoilhat/tinfoil-sms#15]
## Issue

After two users import each other as trusted contacts and the sender initiates the key exchange with the recipient using the exchange button in the message view and entering the shared secrets the recipient will have a NullPointerException on receiving the key exchange.
## How to Replicate
1. Have both users import each other as trusted contacts (using real phones not the emulator).
2. Have user 1 (the initiator) go to the message view and press the "Exchange" button and enter the two shared secrets.
3. User 2 (the recipient) will have a NullPointerException upon receiving the key exchange from user 1.
## Stack Trace

```
java.lang.RuntimeException: Unable to start receiver com.tinfoil.sms.utility.MessageReceiver: java.lang.NullPointerException
at android.app.ActivityThread.handleReceiver(ActivityThread.java:1809)
at android.app.ActivityThread.access$2400(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:985)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.tinfoilsms.crypto.APrioriInfo.<init>(APrioriInfo.java:44)
at com.tinfoil.sms.crypto.KeyExchange.verify(KeyExchange.java:205)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:201)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:1798)
... 10 more
java.lang.NullPointerException
at com.tinfoilsms.crypto.APrioriInfo.<init>(APrioriInfo.java:44)
at com.tinfoil.sms.crypto.KeyExchange.verify(KeyExchange.java:205)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:201)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:1798)
at android.app.ActivityThread.access$2400(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:985)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```
## ACRA's Analysis of the root cause of the issue

```
digest      java.lang.RuntimeException: Unable to start receiver com.tinfoil.sms.utility.MessageReceiver: java.lang.NullPointerException : KeyExchange.java:205
full        java.lang.RuntimeException: Unable to start receiver com.tinfoil.sms.utility.MessageReceiver: java.lang.NullPointerException at com.tinfoil.sms.crypto.KeyExchange.verify(KeyExchange.java:205)
rootCause   java.lang.NullPointerException at com.tinfoil.sms.crypto.KeyExchange.verify(KeyExchange.java:205)
```

**Comment by dataBaseError** [comment]
This problem is because neither user has set there shared secrets. Once the key exchange is sent my the first user they will set their shared secrets. However the other user's shared secrets are still not set and thus would cause a null pointer exception (since there was no check). 

This has been fixed in 6befc729704cfc5630b4dd6ad94f899af04da0f4

Now if the user receives a key exchange and does not a shared secret for that contact the message will be redirected to the KeyExchangeManager activity to be handled automatically. If the user attempts to accept the key exchange from a user, but have not yet set their shared secrets a pop-up dialogue (exactly the same as the message view one on sent of key exchange) will show up to allow the user to set the contact's shared secrets.
