### ISSUE TITLE
org.spongycastle.crypto.InvalidCipherTextException: Length of input must be greater than the MAC

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#27]
``` bash
org.spongycastle.crypto.InvalidCipherTextException: Length of input must be greater than the MAC
at org.spongycastle.crypto.engines.IESEngine.decryptBlock(IESEngine.java:146)
at org.spongycastle.crypto.engines.IESEngine.processBlock(IESEngine.java:316)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:184)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:168)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:169)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2376)
at android.app.ActivityThread.access$1500(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5039)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
org.spongycastle.crypto.InvalidCipherTextException: Length of input must be greater than the MAC
at org.spongycastle.crypto.engines.IESEngine.decryptBlock(IESEngine.java:146)
at org.spongycastle.crypto.engines.IESEngine.processBlock(IESEngine.java:316)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:184)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:168)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:169)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2376)
at android.app.ActivityThread.access$1500(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5039)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by gnu-user** [comment]
This is not an issue, but a properly handled exception that occurs if a person untrusts the other contact and then attempts to send a plaintext message to them that is smaller than the length of the MAC (32 bytes). This can also occur if the other trusted contact sends a plaintext message that is smaller than the length of the MAC by using the native SMS messaging application rather than Tinfoil-SMS.

This exception is logged by Bugsense as we record all exceptions that occur at MessageReceiver.onReceive().
