### ISSUE TITLE
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#33]
``` bash
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
at com.tinfoil.sms.database.DBAccessor.getNumber(DBAccessor.java:943)
at com.tinfoil.sms.database.DBAccessor.isTrustedContact(DBAccessor.java:1455)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:204)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:856)
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
at com.tinfoil.sms.database.DBAccessor.getNumber(DBAccessor.java:943)
at com.tinfoil.sms.database.DBAccessor.isTrustedContact(DBAccessor.java:1455)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:204)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:856)

```

**Comment by dataBaseError** [comment]
Added content provider in 782562b4974801e3f95387b9782be06f1a3cf313 which should solve this and other database related problems.
