### ISSUE TITLE
org.spongycastle.crypto.InvalidCipherTextException: Mac codes failed to equal.

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#35]
``` bash
org.spongycastle.crypto.InvalidCipherTextException: Mac codes failed to equal.
at org.spongycastle.crypto.engines.IESEngine.decryptBlock(IESEngine.java:210)
at org.spongycastle.crypto.engines.IESEngine.processBlock(IESEngine.java:316)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:184)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:168)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:186)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2810)
at android.app.ActivityThread.access$3200(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
org.spongycastle.crypto.InvalidCipherTextException: Mac codes failed to equal.
at org.spongycastle.crypto.engines.IESEngine.decryptBlock(IESEngine.java:210)
at org.spongycastle.crypto.engines.IESEngine.processBlock(IESEngine.java:316)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:184)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:168)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:186)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2810)
at android.app.ActivityThread.access$3200(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by gnu-user** [comment]
This issue appears to only occur when using the Android emulator due to a bug in the emulator that sometimes scrambles the encrypted messages, this error has never occurred anywhere else. However, this is not actually an error but a handled exception, and can occur if a service provider is scrambling SMS messages resulting in the MAC (Message Authentication Code) not matching!

**Comment by gnu-user** [comment]
This can also occur when someone has a contact as trusted and they receive an unencrypted message which by a fluke has a valid Nonce counter (e.g. What's up) where "Wh" actually is interpreted as a valid nonce! Which results in attempting to decrypt the message as if it was an encrypted message.

This has been re-opened as it will still be investigated further.
