### ISSUE TITLE
java.lang.RuntimeException: Invalid point encoding 0x-29

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#37]
``` bash
java.lang.RuntimeException: Invalid point encoding 0x-29
at org.spongycastle.math.ec.ECCurve$Fp.decodePoint(ECCurve.java:138)
at com.orwell.crypto.ECGKeyUtil.decodePubKey(ECGKeyUtil.java:156)
at com.orwell.crypto.ECGKeyUtil.decodeBase64PubKey(ECGKeyUtil.java:174)
at com.tinfoil.sms.crypto.Encryption.initECEngine(Encryption.java:243)
at com.tinfoil.sms.crypto.Encryption.encrypt(Encryption.java:97)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:215)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:1019)
java.lang.RuntimeException: Invalid point encoding 0x-29
at org.spongycastle.math.ec.ECCurve$Fp.decodePoint(ECCurve.java:138)
at com.orwell.crypto.ECGKeyUtil.decodePubKey(ECGKeyUtil.java:156)
at com.orwell.crypto.ECGKeyUtil.decodeBase64PubKey(ECGKeyUtil.java:174)
at com.tinfoil.sms.crypto.Encryption.initECEngine(Encryption.java:243)
at com.tinfoil.sms.crypto.Encryption.encrypt(Encryption.java:97)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:215)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:1019)

```

**Comment by gnu-user** [comment]
I cannot seem to debug this no matter what I try, it appears to either be an issue with the BouncyCastle library or a Base64 decoding error. I'm closing this for the current version as it cannot be further investigated without the additional logging added to version 1.3.0 of Tinfoil-SMS.
