### ISSUE TITLE
java.lang.IllegalStateException: attempt to re-open an already-closed object: android.database.sqlite.SQLiteQuery (mSql = SELECT _id, display_name, has_phone_number FROM view_htc_contacts_restricted W

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#39]
``` bash
java.lang.IllegalStateException: attempt to re-open an already-closed object: android.database.sqlite.SQLiteQuery (mSql = SELECT _id, display_name, has_phone_number FROM view_htc_contacts_restricted WHERE ( (( ext_account_Type<>'DeviceOnly' ) OR ( ext_account_Type IS NULL  ) )) ORDER BY display_name) 
at android.os.Parcel.readException(Parcel.java:1330)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:160)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:114)
at android.database.BulkCursorProxy.getWindow(BulkCursorNative.java:217)
at android.database.BulkCursorToCursorAdaptor.onMove(BulkCursorToCursorAdaptor.java:109)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:188)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:256)
at android.database.CursorWrapper.moveToNext(CursorWrapper.java:196)
at com.tinfoil.sms.settings.ImportContactLoader.execution(ImportContactLoader.java:214)
at com.tinfoil.sms.loader.Loader.run(Loader.java:51)
at java.lang.Thread.run(Thread.java:1027)

```

**Comment by dataBaseError** [comment]
Solved with the introduction of the content provider in version 1.3.0
