### ISSUE TITLE
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.tinfoil.sms/databases/tinfoil-sms.db

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#40]
``` bash
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.tinfoil.sms/databases/tinfoil-sms.db
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1184)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1060)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1228)
at com.tinfoil.sms.database.DBAccessor.getNumber(DBAccessor.java:937)
at com.tinfoil.sms.database.DBAccessor.isTrustedContact(DBAccessor.java:1455)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:204)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:856)
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.tinfoil.sms/databases/tinfoil-sms.db
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1184)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1060)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1228)
at com.tinfoil.sms.database.DBAccessor.getNumber(DBAccessor.java:937)
at com.tinfoil.sms.database.DBAccessor.isTrustedContact(DBAccessor.java:1455)
at com.tinfoil.sms.utility.SMSUtility.sendMessage(SMSUtility.java:204)
at com.tinfoil.sms.messageQueue.MessageSender.run(MessageSender.java:149)
at java.lang.Thread.run(Thread.java:856)

```

**Comment by dataBaseError** [comment]
Solved with the introduction of the content provider in version 1.3.0
