### ISSUE TITLE
java.lang.IllegalArgumentException: Layout: -8 < 0

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#43]
``` bash
java.lang.IllegalArgumentException: Layout: -8 < 0
at android.text.Layout.<init>(Layout.java:117)
at android.text.DynamicLayout.<init>(DynamicLayout.java:78)
at android.text.DynamicLayout.<init>(DynamicLayout.java:61)
at android.text.DynamicLayout.<init>(DynamicLayout.java:47)
at com.espian.showcaseview.drawing.TextDrawerImpl.draw(TextDrawerImpl.java:57)
at com.espian.showcaseview.ShowcaseView.dispatchDraw(ShowcaseView.java:418)
at android.view.View.buildDrawingCache(View.java:6758)
at android.view.View.getDrawingCache(View.java:6546)
at android.view.ViewGroup.drawChild(ViewGroup.java:1613)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1415)
at android.view.View.draw(View.java:7001)
at android.widget.FrameLayout.draw(FrameLayout.java:357)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1893)
at android.view.ViewRoot.draw(ViewRoot.java:1536)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1272)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1885)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3740)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:876)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by gnu-user** [comment]
This is a one off issue with an obscure hardware/custom android combination on a mobile phone (from what I can tell it actually comes normally with Windows 8!). We'll leave this closed and re-open if it ever occurs on any other phones.
