### ISSUE TITLE
org.strippedcastle.crypto.InvalidCipherTextException: Invalid MAC.

### ISSUE THREAD

**Issue by tinfoilhat** [tinfoilhat/tinfoil-sms#45]
``` bash
org.strippedcastle.crypto.InvalidCipherTextException: Invalid MAC.
at org.strippedcastle.crypto.engines.IESEngine.decryptBlock(Unknown Source)
at org.strippedcastle.crypto.engines.IESEngine.processBlock(Unknown Source)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:174)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:181)
at com.tinfoil.sms.utility.MessageReceiver.handleEncryptedMessage(MessageReceiver.java:354)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:125)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2419)
at android.app.ActivityThread.access$1700(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
org.strippedcastle.crypto.InvalidCipherTextException: Invalid MAC.
at org.strippedcastle.crypto.engines.IESEngine.decryptBlock(Unknown Source)
at org.strippedcastle.crypto.engines.IESEngine.processBlock(Unknown Source)
at com.orwell.crypto.ECEngine.processBlock(ECEngine.java:174)
at com.tinfoil.sms.crypto.Encryption.decrypt(Encryption.java:181)
at com.tinfoil.sms.utility.MessageReceiver.handleEncryptedMessage(MessageReceiver.java:354)
at com.tinfoil.sms.utility.MessageReceiver.onReceive(MessageReceiver.java:125)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2419)
at android.app.ActivityThread.access$1700(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by gnu-user** [comment]
This is related to issues with KitKat encoding encrypted messages when testing the 1.4.0-dev branch. For some reason encrypted messages get scrambled similarly to the bug often found when using emulators, but not present on real mobile devices.

**Comment by dataBaseError** [comment]
It is important to note however that the issue with the emulator was only for multi-part messages. For KitKat the issue is encountered for a single message.
